from __future__ import annotations

from .financeiro import FINANCE_ORG_SCOPE_DEFAULT

FINANCE_HTTP_ENVELOPE_FIELDS = (
    "success",
    "status",
    "code",
    "message",
    "request_id",
    "correlation_id",
)

FINANCE_HTTP_ERROR_ENVELOPE_FIELDS = FINANCE_HTTP_ENVELOPE_FIELDS

FINANCE_HTTP_CONTRACTS = (
    {
        "name": "finance_missions_list",
        "method": "GET",
        "path": "/api/v1/financeiro/missoes",
        "permission": "finance:missions:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_missions_create",
        "method": "POST",
        "path": "/api/v1/financeiro/missoes",
        "permission": "finance:missions:create",
        "kind": "mutation",
        "audit_events": ("finance.mission.created",),
        "request_payload_minimal": (
            "competencia",
            "data_missao",
            "cavok_numero_voo",
            "aeronave_id",
            "comandante_tripulante_id",
            "copiloto_tripulante_id",
            "horario_apresentacao",
            "horario_abandono",
        ),
        "response_payload": ("mission", "participants"),
        "success_statuses": (201,),
        "error_statuses": (400, 401, 403, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_by_request_competencia",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_mission_preview",
        "method": "POST",
        "path": "/api/v1/financeiro/missoes/preview",
        "permission": "finance:missions:read",
        "kind": "simulation",
        "audit_events": (),
        "request_payload_minimal": (
            "competencia",
            "data_missao",
            "aeronave_id",
            "categoria_financeira_aeronave",
            "comandante_tripulante_id",
            "copiloto_tripulante_id",
            "horario_apresentacao",
            "horario_abandono",
        ),
        "response_payload": ("preview",),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "simulation_does_not_mutate_closed_period",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_mission_detail",
        "method": "GET",
        "path": "/api/v1/financeiro/missoes/{id}",
        "permission": "finance:missions:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("mission", "participants", "hourly_bonus_calculations"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 404),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_mission_preflight",
        "method": "GET",
        "path": "/api/v1/financeiro/missoes/{id}/preflight-calculo",
        "permission": "finance:missions:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("data",),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_mission_update",
        "method": "PATCH",
        "path": "/api/v1/financeiro/missoes/{id}",
        "permission": "finance:missions:update",
        "kind": "mutation",
        "audit_events": ("finance.mission.updated",),
        "request_payload_minimal": ("changed_fields", "motivo"),
        "response_payload": ("mission", "participants"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_mission_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_mission_recalculate",
        "method": "POST",
        "path": "/api/v1/financeiro/missoes/{id}/recalcular",
        "permission": "finance:missions:recalculate",
        "kind": "mutation",
        "audit_events": (
            "finance.mission.recalculation.requested",
            "finance.mission.recalculated",
            "finance.calculation.updated",
            "finance.calculation.superseded",
            "finance.calculation.failed",
            "finance.hourly_bonus.calculated",
        ),
        "request_payload_minimal": ("motivo", "expected_calculation_version"),
        "response_payload": (
            "mission",
            "calculations",
            "mission_id",
            "competence",
            "calculation_status",
            "recalculated_at",
            "affected_calculations",
            "warnings",
            "errors",
            "current_result",
            "audit_event_id",
        ),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_mission_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_mission_cancel",
        "method": "POST",
        "path": "/api/v1/financeiro/missoes/{id}/cancelar",
        "permission": "finance:missions:cancel",
        "kind": "mutation",
        "audit_events": (
            "finance.mission.cancel.requested",
            "finance.mission.cancelled",
            "finance.calculation.invalidated_by_mission_cancel",
            "finance.mission.cancel.failed",
        ),
        "request_payload_minimal": ("motivo",),
        "response_payload": (
            "mission",
            "mission_id",
            "competence",
            "calculation_status",
            "affected_calculations",
            "warnings",
            "errors",
            "current_result",
        ),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_mission_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_grid_list",
        "method": "GET",
        "path": "/api/v1/financeiro/lancamentos-jornada",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": ("finance.journey_grid.generated",),
        "request_payload_minimal": (),
        "response_payload": ("contexto", "indicadores", "linhas", "permissoes", "status_competencia"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_line_create",
        "method": "POST",
        "path": "/api/v1/financeiro/lancamentos-jornada",
        "permission": "finance:missions:create",
        "kind": "mutation",
        "audit_events": ("finance.journey_line.created", "finance.mission.created"),
        "request_payload_minimal": (
            "competencia",
            "data",
            "tripulante_id",
            "funcao",
            "aeronave_id",
            "hora_apresentacao",
            "hora_abandono",
        ),
        "response_payload": ("linha", "mission"),
        "success_statuses": (201,),
        "error_statuses": (400, 401, 403, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_by_request_competencia",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_line_preview",
        "method": "POST",
        "path": "/api/v1/financeiro/lancamentos-jornada/preview",
        "permission": "finance:bonuses:read",
        "kind": "simulation",
        "audit_events": (),
        "request_payload_minimal": (
            "competencia",
            "data",
            "tripulante_id",
            "funcao",
            "aeronave_id",
            "hora_apresentacao",
            "hora_abandono",
        ),
        "response_payload": ("preview",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "simulation_does_not_mutate_closed_period",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_grid_recalculate",
        "method": "POST",
        "path": "/api/v1/financeiro/lancamentos-jornada/recalcular-grade",
        "permission": "finance:periods:recalculate",
        "kind": "mutation",
        "audit_events": (
            "finance.journey_grid.recalculated",
            "finance.mission.recalculated",
            "finance.calculation.updated",
            "finance.period.recalculated",
            "finance.productivity.calculated",
        ),
        "request_payload_minimal": ("competencia",),
        "response_payload": ("contexto", "indicadores", "linhas", "recalculation"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_grid_pdf",
        "method": "GET",
        "path": "/api/v1/financeiro/lancamentos-jornada.pdf",
        "permission": "finance:exports:create",
        "kind": "export",
        "audit_events": ("finance.export.generated", "finance.journey_grid.exported"),
        "request_payload_minimal": ("competencia",),
        "response_payload": ("application/pdf",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_persisted_calculations_only",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_total_flight_hours",
        "method": "GET",
        "path": "/api/v1/financeiro/horas-totais-voadas",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": ("competencia", "funcao"),
        "response_payload": ("contexto", "linhas", "totais", "filters"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_total_flight_hours_pdf",
        "method": "GET",
        "path": "/api/v1/financeiro/horas-totais-voadas.pdf",
        "permission": "finance:exports:create",
        "kind": "export",
        "audit_events": ("finance.export.generated",),
        "request_payload_minimal": ("competencia", "funcao"),
        "response_payload": ("application/pdf",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_persisted_calculations_only",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_line_update",
        "method": "PATCH",
        "path": "/api/v1/financeiro/lancamentos-jornada/{id}",
        "permission": "finance:missions:update",
        "kind": "mutation",
        "audit_events": ("finance.journey_line.updated", "finance.mission.updated"),
        "request_payload_minimal": ("changed_fields",),
        "response_payload": ("linha", "mission"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_mission_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_journey_line_recalculate",
        "method": "POST",
        "path": "/api/v1/financeiro/lancamentos-jornada/{id}/recalcular",
        "permission": "finance:missions:recalculate",
        "kind": "mutation",
        "audit_events": (
            "finance.journey_line.recalculated",
            "finance.mission.recalculated",
            "finance.calculation.updated",
        ),
        "request_payload_minimal": ("motivo",),
        "response_payload": ("linha", "recalculation"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_mission_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_hourly_bonuses_list",
        "method": "GET",
        "path": "/api/v1/financeiro/bonificacoes/horaria",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_hourly_bonus_detail",
        "method": "GET",
        "path": "/api/v1/financeiro/bonificacoes/horaria/{id}",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("hourly_bonus_calculation", "memoria_calculo"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 404),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_productivity_bonuses_list",
        "method": "GET",
        "path": "/api/v1/financeiro/bonificacoes/produtividade",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_productivity_consolidated",
        "method": "GET",
        "path": "/api/v1/financeiro/produtividade/consolidado",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": ("competencia",),
        "response_payload": (
            "contexto",
            "indicadores",
            "linhas_por_tripulante",
            "totais_por_funcao",
            "alertas",
            "bloqueios",
            "condicoes_especiais",
        ),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_productivity_bonus_by_tripulante",
        "method": "GET",
        "path": "/api/v1/financeiro/bonificacoes/produtividade/{tripulante_id}",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("productivity_bonus_calculation", "memoria_calculo"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 404, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_individual_report_pdf",
        "method": "GET",
        "path": "/api/v1/financeiro/relatorios/individual.pdf",
        "permission": "finance:exports:create",
        "kind": "export",
        "audit_events": ("finance.export.generated", "finance.report.individual.generated"),
        "request_payload_minimal": ("tipo", "competencia", "tripulante_id"),
        "response_payload": ("application/pdf",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_persisted_calculations_only",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_productivity_general_report",
        "method": "GET",
        "path": "/api/v1/financeiro/produtividade/relatorio-geral",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": ("competencia", "funcao"),
        "response_payload": ("competencia", "funcao", "titulo", "totais", "items", "pendencias", "filters"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_productivity_general_report_pdf",
        "method": "GET",
        "path": "/api/v1/financeiro/produtividade/relatorio-geral.pdf",
        "permission": "finance:exports:create",
        "kind": "export",
        "audit_events": ("finance.export.generated",),
        "request_payload_minimal": ("competencia", "funcao"),
        "response_payload": ("application/pdf",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_persisted_calculations_only",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_extract",
        "method": "GET",
        "path": "/api/v1/financeiro/extrato-periodo",
        "permission": "finance:bonuses:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": ("data_inicio", "data_fim"),
        "response_payload": ("contexto", "linhas", "subtotais", "total_geral", "alertas"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_extract_pdf",
        "method": "GET",
        "path": "/api/v1/financeiro/extrato-periodo.pdf",
        "permission": "finance:exports:create",
        "kind": "export",
        "audit_events": ("finance.extract.period.generated",),
        "request_payload_minimal": ("data_inicio", "data_fim"),
        "response_payload": ("application/pdf",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_detail",
        "method": "GET",
        "path": "/api/v1/financeiro/competencias/{competencia}",
        "permission": "finance:periods:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("period", "totals", "snapshot", "divergences"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_preflight",
        "method": "GET",
        "path": "/api/v1/financeiro/competencias/{competencia}/preflight-calculo",
        "permission": "finance:periods:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("data",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_report_pdf",
        "method": "GET",
        "path": "/api/v1/financeiro/competencias/{competencia}/relatorio.pdf",
        "permission": "finance:exports:create",
        "kind": "export",
        "audit_events": ("finance.export.generated",),
        "request_payload_minimal": (),
        "response_payload": ("application/pdf",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "closed_period_uses_snapshot_without_recalculation",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_recalculate",
        "method": "POST",
        "path": "/api/v1/financeiro/competencias/{competencia}/recalcular",
        "permission": "finance:periods:recalculate",
        "kind": "mutation",
        "audit_events": ("finance.period.recalculated", "finance.productivity.calculated"),
        "request_payload_minimal": ("motivo", "expected_calculation_version"),
        "response_payload": ("period", "totals", "divergences", "calculation_memory"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_competencia_is_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_close",
        "method": "POST",
        "path": "/api/v1/financeiro/competencias/{competencia}/fechar",
        "permission": "finance:periods:close",
        "kind": "mutation",
        "audit_events": ("finance.period.closed",),
        "request_payload_minimal": ("confirm", "motivo", "expected_calculation_version"),
        "response_payload": ("period", "snapshot", "totals"),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": True,
        "closed_period_rule": "blocked_when_competencia_already_fechada",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_period_reopen",
        "method": "POST",
        "path": "/api/v1/financeiro/competencias/{competencia}/reabrir",
        "permission": "finance:periods:reopen",
        "kind": "mutation",
        "audit_events": ("finance.period.reopened",),
        "request_payload_minimal": ("motivo",),
        "response_payload": ("period",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409),
        "blocked_when_period_closed": False,
        "closed_period_rule": "allowed_only_when_closed_with_reason",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_parameters_list",
        "method": "GET",
        "path": "/api/v1/financeiro/parametros",
        "permission": "finance:parameters:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_parameters_create",
        "method": "POST",
        "path": "/api/v1/financeiro/parametros",
        "permission": "finance:parameters:create",
        "kind": "mutation",
        "audit_events": ("finance.parameter.created",),
        "request_payload_minimal": ("tipo", "valor", "unidade", "vigencia_inicio", "motivo"),
        "response_payload": ("parameter",),
        "success_statuses": (201,),
        "error_statuses": (400, 401, 403, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "closed_snapshots_are_not_mutated_by_parameter_change",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_parameters_update",
        "method": "PATCH",
        "path": "/api/v1/financeiro/parametros/{id}",
        "permission": "finance:parameters:update",
        "kind": "mutation",
        "audit_events": ("finance.parameter.updated",),
        "request_payload_minimal": ("changed_fields", "motivo"),
        "response_payload": ("parameter",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "closed_snapshots_are_not_mutated_by_parameter_change",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_holidays_list",
        "method": "GET",
        "path": "/api/v1/financeiro/feriados",
        "permission": "finance:parameters:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_holidays_create",
        "method": "POST",
        "path": "/api/v1/financeiro/feriados",
        "permission": "finance:parameters:create",
        "kind": "mutation",
        "audit_events": ("finance.parameter.created",),
        "request_payload_minimal": ("data", "descricao", "motivo"),
        "response_payload": ("holiday",),
        "success_statuses": (201,),
        "error_statuses": (400, 401, 403, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "closed_snapshots_are_not_mutated_by_calendar_change",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_holidays_update",
        "method": "PATCH",
        "path": "/api/v1/financeiro/feriados/{id}",
        "permission": "finance:parameters:update",
        "kind": "mutation",
        "audit_events": ("finance.parameter.updated",),
        "request_payload_minimal": ("changed_fields", "motivo"),
        "response_payload": ("holiday",),
        "success_statuses": (200,),
        "error_statuses": (400, 401, 403, 404, 409, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "closed_snapshots_are_not_mutated_by_calendar_change",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_audit_list",
        "method": "GET",
        "path": "/api/v1/financeiro/auditoria",
        "permission": "finance:audit:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
    {
        "name": "finance_divergences_list",
        "method": "GET",
        "path": "/api/v1/financeiro/divergencias",
        "permission": "finance:divergences:read",
        "kind": "read_only",
        "audit_events": (),
        "request_payload_minimal": (),
        "response_payload": ("items", "pagination", "filters"),
        "success_statuses": (200,),
        "error_statuses": (401, 403, 422),
        "blocked_when_period_closed": False,
        "closed_period_rule": "read_allowed",
        "requires_org_scope": True,
        "org_scope_default": FINANCE_ORG_SCOPE_DEFAULT,
        "deny_by_default": True,
    },
)


FINANCE_STUB_HTTP_CONTRACTS: tuple[dict, ...] = ()

# Backward-compatible alias kept to avoid breaking imports while callers migrate.
FUTURE_FINANCE_HTTP_CONTRACTS = FINANCE_HTTP_CONTRACTS


def finance_http_contracts() -> tuple[dict, ...]:
    return FINANCE_HTTP_CONTRACTS


def finance_http_paths() -> tuple[str, ...]:
    return tuple(contract["path"] for contract in FINANCE_HTTP_CONTRACTS)


def finance_stub_http_contracts() -> tuple[dict, ...]:
    return FINANCE_STUB_HTTP_CONTRACTS


def finance_stub_http_paths() -> tuple[str, ...]:
    return tuple(contract["path"] for contract in FINANCE_STUB_HTTP_CONTRACTS)


def future_finance_http_contracts() -> tuple[dict, ...]:
    return finance_http_contracts()


def future_finance_http_paths() -> tuple[str, ...]:
    return finance_http_paths()
