from __future__ import annotations

FINANCE_AUDIT_COMMON_METADATA_FIELDS = (
    "event_name",
    "org_id",
    "request_id",
    "correlation_id",
    "actor_user_id",
    "entity_type",
    "entity_id",
    "permission",
    "source_endpoint",
)

FINANCE_AUDIT_EVENT_CATALOG = (
    {
        "event_name": "finance.mission.created",
        "entity_type": "finance_mission",
        "permission": "finance:missions:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "comandante_tripulante_id",
            "copiloto_tripulante_id",
        ),
    },
    {
        "event_name": "finance.mission.updated",
        "entity_type": "finance_mission",
        "permission": "finance:missions:update",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "changed_fields",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.cancel.requested",
        "entity_type": "finance_mission",
        "permission": "finance:missions:cancel",
        "requires_before": True,
        "requires_after": False,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.cancelled",
        "entity_type": "finance_mission",
        "permission": "finance:missions:cancel",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.cancel.failed",
        "entity_type": "finance_mission",
        "permission": "finance:missions:cancel",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "error_code",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.delete.requested",
        "entity_type": "finance_mission",
        "permission": "finance:missions:delete",
        "requires_before": True,
        "requires_after": False,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.deleted",
        "entity_type": "finance_mission",
        "permission": "finance:missions:delete",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.delete.blocked",
        "entity_type": "finance_mission",
        "permission": "finance:missions:delete",
        "requires_before": True,
        "requires_after": False,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.delete.failed",
        "entity_type": "finance_mission",
        "permission": "finance:missions:delete",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "error_code",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.recalculation.requested",
        "entity_type": "finance_mission",
        "permission": "finance:missions:recalculate",
        "requires_before": True,
        "requires_after": False,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.mission.recalculated",
        "entity_type": "finance_mission",
        "permission": "finance:missions:recalculate",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "calculation_version",
            "reason",
        ),
    },
    {
        "event_name": "finance.calculation.updated",
        "entity_type": "finance_hourly_bonus",
        "permission": "finance:missions:recalculate",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "tripulante_id",
            "funcao",
            "calculation_version",
        ),
    },
    {
        "event_name": "finance.calculation.superseded",
        "entity_type": "finance_hourly_bonus",
        "permission": "finance:missions:recalculate",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "tripulante_id",
            "funcao",
            "calculation_version",
        ),
    },
    {
        "event_name": "finance.calculation.invalidated_by_mission_cancel",
        "entity_type": "finance_hourly_bonus",
        "permission": "finance:missions:cancel",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "tripulante_id",
            "funcao",
            "calculation_version",
        ),
    },
    {
        "event_name": "finance.calculation.failed",
        "entity_type": "finance_hourly_bonus",
        "permission": "finance:missions:recalculate",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "error_code",
        ),
    },
    {
        "event_name": "finance.hourly_bonus.calculated",
        "entity_type": "finance_hourly_bonus",
        "permission": "finance:missions:recalculate",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "mission_id",
            "tripulante_id",
            "funcao",
            "calculation_version",
        ),
    },
    {
        "event_name": "finance.productivity.calculated",
        "entity_type": "finance_productivity_bonus",
        "permission": "finance:periods:recalculate",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "tripulante_id",
            "calculation_version",
        ),
    },
    {
        "event_name": "finance.parameter.created",
        "entity_type": "finance_parameter",
        "allowed_entity_types": ("finance_parameter", "finance_holiday"),
        "permission": "finance:parameters:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "tipo",
            "vigencia_inicio",
            "vigencia_fim",
            "reason",
        ),
    },
    {
        "event_name": "finance.parameter.updated",
        "entity_type": "finance_parameter",
        "allowed_entity_types": ("finance_parameter", "finance_holiday"),
        "permission": "finance:parameters:update",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "tipo",
            "changed_fields",
            "reason",
        ),
    },
    {
        "event_name": "finance.period.recalculated",
        "entity_type": "finance_period",
        "permission": "finance:periods:recalculate",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "calculation_version",
            "mission_count",
            "participant_count",
        ),
    },
    {
        "event_name": "finance.period.closed",
        "entity_type": "finance_period",
        "permission": "finance:periods:close",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "snapshot_id",
            "closed_at",
            "total_geral",
        ),
    },
    {
        "event_name": "finance.period.reopened",
        "entity_type": "finance_period",
        "permission": "finance:periods:reopen",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "reason",
            "previous_snapshot_id",
        ),
    },
    {
        "event_name": "finance.journey_grid.generated",
        "entity_type": "finance_journey_grid",
        "permission": "finance:bonuses:read",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "filters",
            "record_count",
        ),
    },
    {
        "event_name": "finance.journey_line.created",
        "entity_type": "finance_journey_line",
        "permission": "finance:missions:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "linha_id",
            "mission_id",
        ),
    },
    {
        "event_name": "finance.journey_line.updated",
        "entity_type": "finance_journey_line",
        "permission": "finance:missions:update",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "linha_id",
            "mission_id",
        ),
    },
    {
        "event_name": "finance.journey_line.cancelled",
        "entity_type": "finance_journey_line",
        "permission": "finance:missions:cancel",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "linha_id",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.journey_line.deleted",
        "entity_type": "finance_journey_line",
        "permission": "finance:missions:delete",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "linha_id",
            "mission_id",
            "reason",
        ),
    },
    {
        "event_name": "finance.journey_line.recalculated",
        "entity_type": "finance_journey_line",
        "permission": "finance:missions:recalculate",
        "requires_before": True,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "linha_id",
            "mission_id",
        ),
    },
    {
        "event_name": "finance.journey_grid.recalculated",
        "entity_type": "finance_journey_grid",
        "permission": "finance:periods:recalculate",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "filters",
            "record_count",
        ),
    },
    {
        "event_name": "finance.journey_grid.exported",
        "entity_type": "finance_journey_grid",
        "permission": "finance:exports:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "format",
            "filters",
            "record_count",
        ),
    },
    {
        "event_name": "finance.extract.period.generated",
        "entity_type": "finance_export",
        "permission": "finance:exports:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "format",
            "filters",
            "record_count",
        ),
    },
    {
        "event_name": "finance.productivity.consolidated.generated",
        "entity_type": "finance_productivity_bonus",
        "permission": "finance:bonuses:read",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "filters",
            "record_count",
        ),
    },
    {
        "event_name": "finance.report.individual.generated",
        "entity_type": "finance_export",
        "permission": "finance:exports:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "format",
            "filters",
            "record_count",
        ),
    },
    {
        "event_name": "finance.export.generated",
        "entity_type": "finance_export",
        "permission": "finance:exports:create",
        "requires_before": False,
        "requires_after": True,
        "required_metadata": (
            *FINANCE_AUDIT_COMMON_METADATA_FIELDS,
            "competencia",
            "format",
            "filters",
            "record_count",
        ),
    },
)

FINANCE_AUDIT_EVENT_NAMES = tuple(event["event_name"] for event in FINANCE_AUDIT_EVENT_CATALOG)

FINANCE_AUDIT_EVENTS_BY_NAME = {
    event["event_name"]: event
    for event in FINANCE_AUDIT_EVENT_CATALOG
}
